// Command notices generates the third-party notices shipped with Corsarr
// Desktop from the modules that are actually part of its Go dependency graph.
package main

import (
	"bufio"
	"bytes"
	"encoding/json"
	"flag"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"sort"
	"strings"
)

type module struct {
	Path    string
	Version string
	Dir     string
	Main    bool
	Replace *module
}

type listedPackage struct {
	Module *module
}

type dependency struct {
	Path         string
	Version      string
	Dir          string
	LicenseFiles []string
}

const goLicense = `Copyright 2009 The Go Authors. All rights reserved.

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions are
met:

   * Redistributions of source code must retain the above copyright
notice, this list of conditions and the following disclaimer.
   * Redistributions in binary form must reproduce the above
copyright notice, this list of conditions and the following disclaimer
in the documentation and/or other materials provided with the
distribution.
   * Neither the name of Google Inc. nor the names of its
contributors may be used to endorse or promote products derived from
this software without specific prior written permission.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
"AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
(INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.`

func main() {
	output := flag.String("output", "THIRD_PARTY_NOTICES.md", "generated notice file")
	flag.Parse()

	dependencies, err := desktopDependencies()
	if err != nil {
		fatal(err)
	}

	content, err := render(dependencies)
	if err != nil {
		fatal(err)
	}
	if err := os.WriteFile(*output, content, 0o644); err != nil {
		fatal(err)
	}
}

func desktopDependencies() ([]dependency, error) {
	command := exec.Command("go", "list", "-deps", "-json", "./desktop")
	output, err := command.Output()
	if err != nil {
		return nil, fmt.Errorf("list desktop dependencies: %w", err)
	}

	decoder := json.NewDecoder(bytes.NewReader(output))
	unique := map[string]dependency{}
	for decoder.More() {
		var pkg listedPackage
		if err := decoder.Decode(&pkg); err != nil {
			return nil, fmt.Errorf("decode go list output: %w", err)
		}
		if pkg.Module == nil || pkg.Module.Main {
			continue
		}

		selected := pkg.Module
		if selected.Replace != nil {
			selected = selected.Replace
		}
		files, err := licenseFiles(selected.Dir)
		if err != nil {
			return nil, fmt.Errorf("find license for %s: %w", pkg.Module.Path, err)
		}
		if len(files) == 0 {
			return nil, fmt.Errorf("dependency %s has no root license file", pkg.Module.Path)
		}

		version := pkg.Module.Version
		if version == "" {
			version = selected.Version
		}
		unique[pkg.Module.Path] = dependency{
			Path:         pkg.Module.Path,
			Version:      version,
			Dir:          selected.Dir,
			LicenseFiles: files,
		}
	}

	dependencies := make([]dependency, 0, len(unique))
	for _, item := range unique {
		dependencies = append(dependencies, item)
	}
	sort.Slice(dependencies, func(i, j int) bool {
		return dependencies[i].Path < dependencies[j].Path
	})
	return dependencies, nil
}

func licenseFiles(directory string) ([]string, error) {
	entries, err := os.ReadDir(directory)
	if err != nil {
		return nil, err
	}

	var files []string
	for _, entry := range entries {
		if entry.IsDir() {
			continue
		}
		name := strings.ToLower(entry.Name())
		if strings.HasPrefix(name, "license") || strings.HasPrefix(name, "copying") || strings.HasPrefix(name, "notice") {
			files = append(files, entry.Name())
		}
	}
	sort.Strings(files)
	return files, nil
}

func render(dependencies []dependency) ([]byte, error) {
	var output bytes.Buffer
	writer := bufio.NewWriter(&output)
	fmt.Fprintln(writer, "# Third-party notices")
	fmt.Fprintln(writer)
	fmt.Fprintln(writer, "This file is generated by `go run ./tools/notices` from the Go modules")
	fmt.Fprintln(writer, "compiled into Corsarr Desktop. Build-only frontend tools are not redistributed.")
	fmt.Fprintln(writer, "Media applications and container images downloaded after installation are not")
	fmt.Fprintln(writer, "bundled with Corsarr and are credited separately in the Desktop licenses screen.")
	fmt.Fprintln(writer)
	fmt.Fprintln(writer, "| Dependency | Version |")
	fmt.Fprintln(writer, "| --- | --- |")
	fmt.Fprintln(writer, "| `Go standard library` | release build toolchain |")
	for _, item := range dependencies {
		fmt.Fprintf(writer, "| `%s` | `%s` |\n", item.Path, item.Version)
	}

	fmt.Fprintln(writer)
	fmt.Fprintln(writer, "## Go standard library")
	fmt.Fprintln(writer)
	fmt.Fprintln(writer, "```text")
	fmt.Fprintln(writer, goLicense)
	fmt.Fprintln(writer, "```")

	for _, item := range dependencies {
		fmt.Fprintln(writer)
		fmt.Fprintf(writer, "## %s %s\n", item.Path, item.Version)
		for _, name := range item.LicenseFiles {
			license, err := os.ReadFile(filepath.Join(item.Dir, name))
			if err != nil {
				return nil, err
			}
			fmt.Fprintln(writer)
			fmt.Fprintf(writer, "Source file: `%s`\n\n", name)
			fmt.Fprintln(writer, "```text")
			fmt.Fprintln(writer, strings.TrimSpace(string(license)))
			fmt.Fprintln(writer, "```")
		}
	}

	if err := writer.Flush(); err != nil {
		return nil, err
	}
	return output.Bytes(), nil
}

func fatal(err error) {
	fmt.Fprintln(os.Stderr, err)
	os.Exit(1)
}
