// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AcceptCurrentTerms() {
  return window['go']['main']['App']['AcceptCurrentTerms']();
}

export function ChooseStorageLocation() {
  return window['go']['main']['App']['ChooseStorageLocation']();
}

export function GetApplicationStatuses() {
  return window['go']['main']['App']['GetApplicationStatuses']();
}

export function GetEnvironmentStatus() {
  return window['go']['main']['App']['GetEnvironmentStatus']();
}

export function GetSetupStatus() {
  return window['go']['main']['App']['GetSetupStatus']();
}

export function InstallSelectedApplications() {
  return window['go']['main']['App']['InstallSelectedApplications']();
}

export function ListApplications() {
  return window['go']['main']['App']['ListApplications']();
}

export function OpenApplication(arg1) {
  return window['go']['main']['App']['OpenApplication'](arg1);
}

export function PrepareStorageLayout() {
  return window['go']['main']['App']['PrepareStorageLayout']();
}

export function RemoveApplication(arg1) {
  return window['go']['main']['App']['RemoveApplication'](arg1);
}

export function RestartApplication(arg1) {
  return window['go']['main']['App']['RestartApplication'](arg1);
}

export function SaveApplicationSelection(arg1) {
  return window['go']['main']['App']['SaveApplicationSelection'](arg1);
}

export function StartApplication(arg1) {
  return window['go']['main']['App']['StartApplication'](arg1);
}

export function StopApplication(arg1) {
  return window['go']['main']['App']['StopApplication'](arg1);
}
