// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {application} from '../models';
import {storage} from '../models';

export function AcceptCurrentTerms():Promise<application.SetupStatus>;

export function ArchiveApplicationData(arg1:string):Promise<storage.ArchivedApplicationData>;

export function ChooseStorageLocation():Promise<storage.Status>;

export function CopyQBittorrentPassword():Promise<void>;

export function GetApplicationDataStatuses():Promise<Array<storage.ApplicationDataStatus>>;

export function GetApplicationStatuses():Promise<Array<application.ManagedApplicationStatus>>;

export function GetEnvironmentStatus():Promise<application.EnvironmentStatus>;

export function GetQBittorrentAccessStatus():Promise<application.ServiceAccessStatus>;

export function GetSetupStatus():Promise<application.SetupStatus>;

export function InstallSelectedApplications():Promise<application.InstallationResult>;

export function ListApplications():Promise<Array<application.ApplicationSummary>>;

export function OpenApplication(arg1:string):Promise<void>;

export function PrepareStorageLayout():Promise<storage.LayoutStatus>;

export function RemoveApplication(arg1:string):Promise<void>;

export function RestartApplication(arg1:string):Promise<void>;

export function SaveApplicationSelection(arg1:Array<string>):Promise<application.SetupStatus>;

export function StartApplication(arg1:string):Promise<void>;

export function StopApplication(arg1:string):Promise<void>;
