// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {application} from '../models';

export function ListApplications():Promise<Array<application.ApplicationSummary>>;

export function OpenApplication(arg1:string):Promise<void>;
