// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {application} from '../models';
import {storage} from '../models';
import {main} from '../models';
import {legal} from '../models';
import {onboarding} from '../models';

export function AcceptCurrentTerms():Promise<application.SetupStatus>;

export function AdvanceOnboarding():Promise<application.SetupStatus>;

export function ArchiveApplicationData(arg1:string):Promise<storage.ArchivedApplicationData>;

export function ChooseStorageLocation():Promise<storage.Status>;

export function CopyJellyfinNetworkURL(arg1:string):Promise<void>;

export function CopyJellyfinPassword():Promise<void>;

export function CopyQBittorrentPassword():Promise<void>;

export function ExportDiagnostics():Promise<main.DiagnosticExportResult>;

export function GetApplicationDataStatuses():Promise<Array<storage.ApplicationDataStatus>>;

export function GetApplicationStatuses():Promise<Array<application.ManagedApplicationStatus>>;

export function GetEnvironmentStatus():Promise<application.EnvironmentStatus>;

export function GetJellyfinAccessStatus():Promise<application.ServiceAccessStatus>;

export function GetJellyfinNetworkStatus():Promise<main.JellyfinNetworkStatus>;

export function GetQBittorrentAccessStatus():Promise<application.ServiceAccessStatus>;

export function GetSetupStatus():Promise<application.SetupStatus>;

export function InstallSelectedApplications():Promise<application.InstallationResult>;

export function ListApplications():Promise<Array<application.ApplicationSummary>>;

export function ListLegalNotices():Promise<Array<legal.Notice>>;

export function OpenApplication(arg1:string):Promise<void>;

export function OpenLegalLink(arg1:string,arg2:string):Promise<void>;

export function OpenStartAtLoginSettings():Promise<void>;

export function PrepareRuntime():Promise<onboarding.PreparationResult>;

export function PrepareStorageLayout():Promise<storage.LayoutStatus>;

export function RemoveApplication(arg1:string):Promise<void>;

export function RestartApplication(arg1:string):Promise<void>;

export function SaveApplicationSelection(arg1:Array<string>):Promise<application.SetupStatus>;

export function SelectRecommendedApplications():Promise<application.SetupStatus>;

export function SetJellyfinLAN(arg1:boolean):Promise<application.SetupStatus>;

export function SetStartAtLogin(arg1:boolean):Promise<application.SetupStatus>;

export function StartApplication(arg1:string):Promise<void>;

export function StopApplication(arg1:string):Promise<void>;

export function UpdateApplication(arg1:string):Promise<application.ApplicationUpdateResult>;
